export enum PermissionEnums {
  CreateOrder = 'create:order',
  UpdateOrder = 'update:order',
  ReadOrder = 'read:order',
  DeleteOrder = 'delete:order',
  CreateProduct = 'create:product',
  UpdateProduct = 'update:product',
  ReadProduct = 'read:product',
  DeleteProduct = 'delete:product',
  CreateUser = 'create:user',
  UpdateUser = 'update:user',
  ReadUser = 'read:user',
  DeleteUser = 'delete:user',
  CreateRole = 'create:role',
  UpdateRole = 'update:role',
  DeleteRole = 'delete:role',
  ReadRole = 'read:role',
}
